# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rainyskye
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Adelaide
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
